#!/bin/bash

# Get the latest tag
LATEST=$(git describe --tags --abbrev=0)

echo "Latest: ${LATEST}"

# Split up the current format into an array using `.` as the delimiter
IFS='.' read -r -a FORMAT <<< "${LATEST}"

YEAR=${FORMAT[0]}
MONTH=${FORMAT[1]}
INDEX=${FORMAT[2]}

# NOTE: For debugging
# echo "Year: ${YEAR}, Month: ${MONTH}, Index: ${INDEX}"

CURRENT_YEAR=$(date -u +'%Y')
CURRENT_MONTH=$(date -u +'%m')

NEXT="${CURRENT_YEAR}.${CURRENT_MONTH}"

# If the current month is different from the latest one
# that means we need to start a new tag with the current month
if [[ "${MONTH}" != "${CURRENT_MONTH}" ]]; then
    NEXT="${NEXT}.0"
else
    # if current month is the same as the latest,
    # bump the index
    NEW_INDEX=$((${INDEX}+1))
    NEXT="${NEXT}.${NEW_INDEX}"
fi

echo "Next: ${NEXT}"
echo

# Tag the repository with the new deployment tag.
# GitHub actions will then deploy the tag.
git tag ${NEXT} && git push origin ${NEXT}
