name: CI build

on: workflow_dispatch
      

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d-%H.%M')" >> $GITHUB_OUTPUT
        
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.date.outputs.date }}
          message: "Latest release"
