name: Build assets for Ovice Tmp Lp

on: workflow_dispatch
      

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          tag: $GITHUB_CONTEXT
          message: "Latest release"
