name: CI build

on:
 push:
      

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get current date
        id: date
        run: |
         sudo apt-get install -y allure
         allure --version
