name: Build assets for Ovice Tmp Lp

on: workflow_dispatch
      

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%dT%H.%M.%S')"
        
      - uses: rickstaa/action-create-tag@v1
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          tag: ${{ steps.date.outputs.date }}
          message: "Latest release"
