name: Node.js CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: check
      run: |
       MY_STRING=$(! grep -R '?\.' resources)
       echo "::set-output name=TAG_NAME::$MY_STRING"
      id: run_tests
    - name: echo PR
      if: ${{ failure() }}
      run: echo ${{steps.run_tests.outputs.TAG_NAME}}
    - name: Comment PR
      if: ${{ failure() }}
      uses: thollander/actions-comment-pull-request@v1 
      with:
          message: " firas ${{steps.run_tests.outputs.TAG_NAME}}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: mattsb42/not-grep@master
      if: ${{ failure() }}
      with:
    # If you don't set config-file the action uses ".github/not-grep.toml".
    # If you don't set debug, passing checks will be hidden.
       debug: true
