name: Node.js CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: check
      run: |
       MY_STRING="$(! grep -R '?\\.' resources)"
       MY_STRING="${MY_STRING//'%'/'%25'}"
       MY_STRING="${MY_STRING//$'\n'/'%0A'}"
       MY_STRING="${MY_STRING//$'\r'/'%0D'}"
       echo "::set-output name=TAG_NAME::$MY_STRING"
      id: run_tests
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1 
      with:
          message: " firas ${{steps.run_tests.outputs.TAG_NAME}}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
