name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: check
      id: ami
      run: |
       MY_STRING="ami-215616566616196"
        echo "::set-output name=deployment_env::$(echo $MY_STRING | grep -o '\w*ami-\w*')"
    - name: install
      run: | 
       echo ${{ steps.ami.outputs.deployment_env }}
