name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: add secret
      id: ami
      run: |
       echo "AWS_REGION=${{GITHUB_REF##*/}}" >> $GITHUB_ENV
    - name: echi
      run: echo $AWS_REGION

