name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: check
      id: ami
      run: |
       MY_STRING="ImageId: ami-006b180665fe4e6ec"
        echo "::set-output name=deployment_env::$(echo $MY_STRING | grep -o 'ami-')"
    - name: install
      run: | 
       echo ${{ steps.ami.outputs.deployment_env }}
