name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: check
      id: ami
      run: |
       echo "ami-0c0f6c4882a0d54af" > ami_name.txt
        echo "::set-output name=deployment_env::$(cat ami_name.txt | grep -o '\w*ami-\w*')"
    - name: install
      run: | 
       echo ${{ steps.ami.outputs.deployment_env }}
