name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
     AWS_REGION: ap-northeast-1
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0
          
    - name: Export current branch
      run: |
        echo "CURRENT_BRANCH=${ GITHUB_REF##*/ }" >> $GITHUB_ENV

