name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: tt
      run: sudo apt-get install rename
    
    - name: try
      run: |
        find ./resources/views/ -name '*.blade.php' -print0 | xargs -0 rename 's/.blade.php$//'
        ls ./resources/views/
    - name: Export current branch
      run: |
        echo 'NEXT_PUBLIC_GA_ID=${{ secrets.TEST }}' >> .env.local
        echo 'NEXT_PUBLIC_FACEBOOK_PIXEL_ID=${{ secrets.TEST2 }}' >> .env.local
        echo "CURRENT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
        cat .env.local
        
    - name: script testing
      run: |
          echo $CURRENT_BRANCH
          case $CURRENT_BRANCH in
          release) echo "AWS_REGION=ap-northeast-1" >> $GITHUB_ENV ;;
          release-eu) echo AWS_REGION=eu-central-1 >> $GITHUB_ENV ;;
          release-us) echo AWS_REGION=us-west-2 >> $GITHUB_ENV ;;
          *) echo "Invalid branch name!" && exit 1 ;;
          esac
    - name: echi
      run: | 
       echo $AWS_REGION

