name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: check
      id: ami
      run: |
       MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
        echo "::set-output name=deployment_env::$(echo $t1 | grep ami)"
    - name: install
      run: | 
       echo ${{ steps.ami.outputs.deployment_env }}
