name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: Get changed directories using defaults
      id: changed-directories
      uses: tj-actions/changed-files@v29.0.7
      with:
        dir_names: true
        
    - name: Run TFLint
      run: |
        for dir in ${{ steps.changed-directories.outputs.all_changed_files }}; do
          ls $dir
        done
