name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: add secret
      id: ami
      run: |
       echo ${{ secrets.TEST }} >> ami_name.txt
       ls *
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
