on: [push]

jobs:
  zap_scan:
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.ovice.com'
          docker_name: 'owasp/zap2docker-stable'
          cmd_options: '-a'
          
      - uses: actions/upload-pages-artifact@v1
        with:
         name: zap_scan
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
            artifact_name: zap_scan
